// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateLocalPlayerRequest struct {
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	College              string   `protobuf:"bytes,6,opt,name=college,proto3" json:"college,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Year                 uint32   `protobuf:"varint,8,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLocalPlayerRequest) Reset()         { *m = CreateLocalPlayerRequest{} }
func (m *CreateLocalPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLocalPlayerRequest) ProtoMessage()    {}
func (*CreateLocalPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateLocalPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLocalPlayerRequest.Unmarshal(m, b)
}
func (m *CreateLocalPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLocalPlayerRequest.Marshal(b, m, deterministic)
}
func (m *CreateLocalPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLocalPlayerRequest.Merge(m, src)
}
func (m *CreateLocalPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLocalPlayerRequest.Size(m)
}
func (m *CreateLocalPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLocalPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLocalPlayerRequest proto.InternalMessageInfo

func (m *CreateLocalPlayerRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateLocalPlayerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLocalPlayerRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateLocalPlayerRequest) GetCollege() string {
	if m != nil {
		return m.College
	}
	return ""
}

func (m *CreateLocalPlayerRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CreateLocalPlayerRequest) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateLocalPlayerRequest)(nil), "protos.CreateLocalPlayerRequest")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xbd, 0x4a, 0xc6, 0x30,
	0x14, 0x86, 0x29, 0x7e, 0x3f, 0xf5, 0x94, 0x0e, 0x1e, 0x1c, 0x42, 0xa7, 0xe2, 0xd4, 0xa9, 0x83,
	0x5e, 0x82, 0xba, 0x39, 0x48, 0x8b, 0x17, 0x10, 0xc3, 0x41, 0x0b, 0x69, 0x53, 0x4f, 0x12, 0x21,
	0x77, 0xe4, 0x65, 0x4a, 0x4f, 0xa8, 0x83, 0xf0, 0x4d, 0x39, 0xcf, 0xf3, 0x26, 0x21, 0x6f, 0x00,
	0xa2, 0x27, 0xee, 0x57, 0x76, 0xc1, 0xe1, 0x49, 0x16, 0xdf, 0x54, 0x31, 0x4c, 0xd6, 0x67, 0x79,
	0xf7, 0x53, 0x80, 0x7a, 0x64, 0xd2, 0x81, 0x5e, 0x9c, 0xd1, 0xf6, 0xd5, 0xea, 0x44, 0x3c, 0xd0,
	0x57, 0x24, 0x1f, 0xb0, 0x81, 0x72, 0x3b, 0xbf, 0xe8, 0x99, 0xd4, 0x55, 0x5b, 0x74, 0xd7, 0xc3,
	0x1f, 0x23, 0xc2, 0x41, 0xfc, 0x41, 0xbc, 0xcc, 0x78, 0x0b, 0xc7, 0xf5, 0xd3, 0x2d, 0xa4, 0x8e,
	0x22, 0x33, 0xa0, 0x82, 0xb3, 0x71, 0xd6, 0xd2, 0x07, 0xa9, 0x93, 0xf8, 0x1d, 0x73, 0x12, 0x97,
	0xc0, 0x49, 0x9d, 0xf7, 0x44, 0x70, 0xbb, 0x3d, 0x91, 0x66, 0x55, 0xb6, 0x45, 0x57, 0x0f, 0x32,
	0xdf, 0x8f, 0x50, 0xbd, 0x79, 0xe2, 0x91, 0xf8, 0x7b, 0x32, 0x84, 0x4f, 0x70, 0x63, 0xfe, 0x3f,
	0x1c, 0xdb, 0x5c, 0xcb, 0xf7, 0x97, 0x3a, 0x35, 0xf5, 0xbe, 0xe3, 0x79, 0x5e, 0x43, 0x7a, 0xcf,
	0x9f, 0xf2, 0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x70, 0x56, 0x19, 0x29, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateLocalPlayer(ctx context.Context, in *CreateLocalPlayerRequest, opts ...grpc.CallOption) (*Empty, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateLocalPlayer(ctx context.Context, in *CreateLocalPlayerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/protos.UserService/createLocalPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateLocalPlayer(context.Context, *CreateLocalPlayerRequest) (*Empty, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateLocalPlayer(ctx context.Context, req *CreateLocalPlayerRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLocalPlayer not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateLocalPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLocalPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateLocalPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.UserService/CreateLocalPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateLocalPlayer(ctx, req.(*CreateLocalPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createLocalPlayer",
			Handler:    _UserService_CreateLocalPlayer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
