# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install
      - run: npm run relay
      - run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UI_HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.UI_PORT }}
          KEY: ${{ secrets.SSHKEYS }}
          PASSWORD: ${{ secrets.SSHKEYS }}
      - run: cd megatreopuz-ui
      - run: git pull
      - run: npm ci
      - run: npm install
      - run: npm run relay
      - run: npm run build --if-present
